Fix __pow__ recursion for s390x compatibility
In Debian, where the tests of this Python package across multiple
architectures, it was discovered that the pairing tests fail on s390x.

Fix the recursion issue by converting FQP.__pow__ from a recursive to an
iterative square-and-multiply implementation. The new implementation is
mathematically equivalent, handles negative exponents (which the old
version didn't), and won't hit maximum recursion depth on large
exponents. With this change tests are fully passing on architecture
s390x in Debian.

Additionally, also convert the FQ classes to use the same iterative
square-and-multiply algorithm. Thehey were not seen failing on s390, but
probably because tests only run with smaller exponents on those
functions.

Also add the `inv` method to both `FQ` classes so that mypy can properly
type check the negative exponent handling in `__pow__` by calling was
calling `self.inv()`.

This is needed to avoid `mypy` failing on:

    py_ecc/fields/optimized_field_elements.py:162: error: Returning Any from function declared to return "T_FQ"  [no-any-return]
    py_ecc/fields/optimized_field_elements.py:162: error: "T_FQ" has no attribute "inv"  [attr-defined]
    py_ecc/fields/field_elements.py:150: error: Returning Any from function declared to return "T_FQ"  [no-any-return]
    py_ecc/fields/field_elements.py:150: error: "T_FQ" has no attribute "inv"  [attr-defined]